volumes:
  mssql-data:
    name: 'mssql-data'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    volumes:
      - mssql-data:/var/opt/mssql
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "admin123"
    restart: unless-stopped
